### ISSUE TITLE
[SC] GS Station Contract Part 2

### ISSUE THREAD

**Issue by vinhnt-a8** [ancient8-gg/space3-web3#37]
#9

**Comment by sangtran-a8** [comment]
- [ ] #Deployment
- [ ] #deposit 
  - [ ] Should allow depositing native token
  - [ ] Should allow depositing ERC20 tokens
  - [ ] Should allow depositing ERC721 tokens
  - [ ] Should allow depositing ERC1155 tokens
- [ ] #setRewardOwner
  - [ ] Should only allow the admin to set rewards
  - [ ] Should set a reward correctly & emit an event
- [ ] #claim
  - [ ] Should let a user claim a reward
  - [ ] Should fail if a reward is already claimed
