### ISSUE TITLE
[SC] GS Station Contract Part 3

### ISSUE THREAD

**Issue by vinhnt-a8** [ancient8-gg/space3-web3#40]

**Comment by sangtran-a8** [comment]
- [x] #Deployment
- [x] #deposit 
  - [x] Should allow depositing native token
  - [x] Should allow depositing ERC20 tokens
  - [x] Should allow depositing ERC721 tokens
  - [x] Should allow depositing ERC1155 tokens
  - [ ] Deposit ERC721 fail
  - [ ] Deposit ERC1155 fail
- [x] #setRewardOwner
  - [x] Should only allow the admin to set rewards (ERC20)
  - [x] Should set a reward correctly & emit an event (ERC20)
  - [ ] Should only allow the admin to set rewards (ERC721)
  - [ ] Should only allow the admin to set rewards (ERC1155)
  - [ ] Set rewards fail cases
- [x] #claim
  - [x] Should let a user claim a reward
  - [x] Should fail if a reward is already claimed
